### ISSUE TITLE
[Doc]: Update doc for "Set up the Documentation"

### ISSUE THREAD

**Issue by lee1043** [tomvothecoder/python-template-repo#5]
### Describe your documentation update

During the Step 3 from [README.rst](https://github.com/tomvothecoder/python-template-repo#readme), step for updating `docs/conf.py` needs to be added to avoid the following issue. 

```
>>> make docs
```

```
rm -rf docs/generated
cd docs && make html
Running Sphinx v5.3.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pcmdi_utils_dev/lib/python3.10/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/Users/lee1043/Documents/Research/git/pcmdi_utils/docs/conf.py", line 24, in <module>
    import python_template
ModuleNotFoundError: No module named 'python_template'

make[1]: *** [html] Error 2
make: *** [docs] Error 2
```

**Comment by lee1043** [comment]
@tomvothecoder I made a quick fix for this but repo does not allow me to create a PR. I'd be happy to provide the minor updated code via email or PR if you are okay with granting me permission. 

```
$ git push -u origin lee1043-patch-1
```

```
ERROR: Permission to tomvothecoder/python-template-repo.git denied to lee1043.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tomvothecoder** [comment]
@lee1043 Thanks for trying out this repo. I added you as a collaborator so you should be able to create a branch directly on the repo now.
